services:
  gpt-sovits:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpt-sovits:latest
    container_name: gpt-sovits-webui
    ports:
      - "9874:9874"  # メインWebUI
      - "9880:9880"  # API
    volumes:
      # プロジェクト全体を共有
      - .:/workspace/GPT-SoVITS
      # 事前学習済みモデル用のボリューム（外部からマウント）
      - models:/workspace/models
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - is_half=True
      - is_share=True
      - language=ja_JP
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  models:
    driver: local
